# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browse_window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 869)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidgetPorocilo = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetPorocilo.setGeometry(QtCore.QRect(10, 0, 851, 831))
        self.tabWidgetPorocilo.setObjectName("tabWidgetPorocilo")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 110, 691, 491))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.dateEdit_DatumOdIskanje = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_DatumOdIskanje.setGeometry(QtCore.QRect(110, 70, 110, 22))
        self.dateEdit_DatumOdIskanje.setObjectName("dateEdit_DatumOdIskanje")
        self.pushButton_delete = QtWidgets.QPushButton(self.tab)
        self.pushButton_delete.setGeometry(QtCore.QRect(610, 610, 81, 23))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_popravi = QtWidgets.QPushButton(self.tab)
        self.pushButton_popravi.setGeometry(QtCore.QRect(750, 740, 91, 23))
        self.pushButton_popravi.setObjectName("pushButton_popravi")
        self.comboBoxZaposleni = QtWidgets.QComboBox(self.tab)
        self.comboBoxZaposleni.setGeometry(QtCore.QRect(20, 70, 71, 20))
        self.comboBoxZaposleni.setEditable(False)
        self.comboBoxZaposleni.setCurrentText("")
        self.comboBoxZaposleni.setObjectName("comboBoxZaposleni")
        self.pushButton_Iskanje = QtWidgets.QPushButton(self.tab)
        self.pushButton_Iskanje.setGeometry(QtCore.QRect(360, 70, 101, 23))
        self.pushButton_Iskanje.setObjectName("pushButton_Iskanje")
        self.dateEdit_DatumDoIskanje = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_DatumDoIskanje.setGeometry(QtCore.QRect(230, 70, 110, 22))
        self.dateEdit_DatumDoIskanje.setObjectName("dateEdit_DatumDoIskanje")
        self.radioButton_ASC = QtWidgets.QRadioButton(self.tab)
        self.radioButton_ASC.setGeometry(QtCore.QRect(600, 50, 82, 17))
        self.radioButton_ASC.setObjectName("radioButton_ASC")
        self.radioButton_DSC = QtWidgets.QRadioButton(self.tab)
        self.radioButton_DSC.setGeometry(QtCore.QRect(600, 80, 82, 17))
        self.radioButton_DSC.setObjectName("radioButton_DSC")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 40, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(260, 40, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(480, 60, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(600, 30, 51, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_izberiNapako = QtWidgets.QPushButton(self.tab)
        self.pushButton_izberiNapako.setGeometry(QtCore.QRect(710, 390, 121, 23))
        self.pushButton_izberiNapako.setObjectName("pushButton_izberiNapako")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 650, 61, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox_ZaposleniImeVnos = QtWidgets.QComboBox(self.tab)
        self.comboBox_ZaposleniImeVnos.setGeometry(QtCore.QRect(10, 710, 71, 20))
        self.comboBox_ZaposleniImeVnos.setEditable(False)
        self.comboBox_ZaposleniImeVnos.setCurrentText("")
        self.comboBox_ZaposleniImeVnos.setObjectName("comboBox_ZaposleniImeVnos")
        self.dateEdit_DatumVnosa = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_DatumVnosa.setGeometry(QtCore.QRect(90, 710, 110, 22))
        self.dateEdit_DatumVnosa.setObjectName("dateEdit_DatumVnosa")
        self.comboBox_DogodekVnos = QtWidgets.QComboBox(self.tab)
        self.comboBox_DogodekVnos.setGeometry(QtCore.QRect(280, 710, 71, 20))
        self.comboBox_DogodekVnos.setEditable(False)
        self.comboBox_DogodekVnos.setCurrentText("")
        self.comboBox_DogodekVnos.setObjectName("comboBox_DogodekVnos")
        self.pushButton_VnosDogodka = QtWidgets.QPushButton(self.tab)
        self.pushButton_VnosDogodka.setGeometry(QtCore.QRect(280, 750, 75, 23))
        self.pushButton_VnosDogodka.setObjectName("pushButton_VnosDogodka")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 690, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(90, 690, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(210, 690, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(280, 690, 47, 13))
        self.label_12.setObjectName("label_12")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(17, 630, 821, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(380, 650, 20, 141))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.timeEdit_UraVnos = QtWidgets.QTimeEdit(self.tab)
        self.timeEdit_UraVnos.setGeometry(QtCore.QRect(210, 710, 61, 22))
        self.timeEdit_UraVnos.setObjectName("timeEdit_UraVnos")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(700, 100, 141, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(700, 590, 141, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.checkBox_zposleni = QtWidgets.QCheckBox(self.tab)
        self.checkBox_zposleni.setGeometry(QtCore.QRect(480, 80, 91, 17))
        self.checkBox_zposleni.setObjectName("checkBox_zposleni")
        self.radioButton_Vse = QtWidgets.QRadioButton(self.tab)
        self.radioButton_Vse.setGeometry(QtCore.QRect(720, 20, 82, 17))
        self.radioButton_Vse.setObjectName("radioButton_Vse")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_Vse)
        self.radioButton_odhod = QtWidgets.QRadioButton(self.tab)
        self.radioButton_odhod.setGeometry(QtCore.QRect(720, 80, 82, 17))
        self.radioButton_odhod.setObjectName("radioButton_odhod")
        self.buttonGroup.addButton(self.radioButton_odhod)
        self.radioButton_prihod = QtWidgets.QRadioButton(self.tab)
        self.radioButton_prihod.setGeometry(QtCore.QRect(720, 50, 82, 17))
        self.radioButton_prihod.setObjectName("radioButton_prihod")
        self.buttonGroup.addButton(self.radioButton_prihod)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(720, 0, 47, 13))
        self.label_14.setObjectName("label_14")
        self.comboBox_ZaposleniImeSpremeni = QtWidgets.QComboBox(self.tab)
        self.comboBox_ZaposleniImeSpremeni.setGeometry(QtCore.QRect(410, 710, 71, 20))
        self.comboBox_ZaposleniImeSpremeni.setEditable(False)
        self.comboBox_ZaposleniImeSpremeni.setCurrentText("")
        self.comboBox_ZaposleniImeSpremeni.setObjectName("comboBox_ZaposleniImeSpremeni")
        self.dateEdit_DatumSpremeni = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_DatumSpremeni.setGeometry(QtCore.QRect(490, 710, 110, 22))
        self.dateEdit_DatumSpremeni.setObjectName("dateEdit_DatumSpremeni")
        self.timeEdit_UraSpremeni = QtWidgets.QTimeEdit(self.tab)
        self.timeEdit_UraSpremeni.setGeometry(QtCore.QRect(610, 710, 61, 22))
        self.timeEdit_UraSpremeni.setObjectName("timeEdit_UraSpremeni")
        self.comboBox_DogodekSpremeni = QtWidgets.QComboBox(self.tab)
        self.comboBox_DogodekSpremeni.setGeometry(QtCore.QRect(680, 710, 71, 20))
        self.comboBox_DogodekSpremeni.setEditable(False)
        self.comboBox_DogodekSpremeni.setCurrentText("")
        self.comboBox_DogodekSpremeni.setObjectName("comboBox_DogodekSpremeni")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(410, 690, 47, 13))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(490, 690, 47, 13))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(610, 690, 47, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(690, 690, 47, 13))
        self.label_18.setObjectName("label_18")
        self.popravi_sporocilo = QtWidgets.QLabel(self.tab)
        self.popravi_sporocilo.setGeometry(QtCore.QRect(416, 752, 271, 21))
        self.popravi_sporocilo.setObjectName("popravi_sporocilo")
        self.vnos_sporocilo = QtWidgets.QLabel(self.tab)
        self.vnos_sporocilo.setGeometry(QtCore.QRect(20, 750, 241, 20))
        self.vnos_sporocilo.setObjectName("vnos_sporocilo")
        self.pushButton_izberiSpremeni = QtWidgets.QPushButton(self.tab)
        self.pushButton_izberiSpremeni.setGeometry(QtCore.QRect(470, 610, 131, 23))
        self.pushButton_izberiSpremeni.setObjectName("pushButton_izberiSpremeni")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(700, 120, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(700, 210, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_vsota1 = QtWidgets.QLabel(self.tab)
        self.label_vsota1.setGeometry(QtCore.QRect(720, 150, 121, 21))
        self.label_vsota1.setObjectName("label_vsota1")
        self.label_vsota2 = QtWidgets.QLabel(self.tab)
        self.label_vsota2.setGeometry(QtCore.QRect(720, 180, 111, 20))
        self.label_vsota2.setObjectName("label_vsota2")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(720, 240, 121, 16))
        self.label_21.setObjectName("label_21")
        self.label_datumIntOd = QtWidgets.QLabel(self.tab)
        self.label_datumIntOd.setGeometry(QtCore.QRect(720, 260, 121, 16))
        self.label_datumIntOd.setObjectName("label_datumIntOd")
        self.label_datumIntDo = QtWidgets.QLabel(self.tab)
        self.label_datumIntDo.setGeometry(QtCore.QRect(720, 300, 121, 16))
        self.label_datumIntDo.setObjectName("label_datumIntDo")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(720, 280, 121, 16))
        self.label_24.setObjectName("label_24")
        self.pushButton_resetfilter = QtWidgets.QPushButton(self.tab)
        self.pushButton_resetfilter.setGeometry(QtCore.QRect(480, 30, 75, 23))
        self.pushButton_resetfilter.setObjectName("pushButton_resetfilter")
        self.pushButton_izracunajPonovno = QtWidgets.QPushButton(self.tab)
        self.pushButton_izracunajPonovno.setGeometry(QtCore.QRect(710, 420, 121, 23))
        self.pushButton_izracunajPonovno.setObjectName("pushButton_izracunajPonovno")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(700, 330, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_napaka = QtWidgets.QLabel(self.tab)
        self.label_napaka.setGeometry(QtCore.QRect(710, 360, 121, 20))
        self.label_napaka.setObjectName("label_napaka")
        self.label_sporociloVsotaUr = QtWidgets.QLabel(self.tab)
        self.label_sporociloVsotaUr.setGeometry(QtCore.QRect(710, 450, 121, 121))
        self.label_sporociloVsotaUr.setWordWrap(True)
        self.label_sporociloVsotaUr.setObjectName("label_sporociloVsotaUr")
        self.tabWidgetPorocilo.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 200, 811, 241))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 450, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(704, 450, 121, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(590, 450, 111, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(510, 450, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(0, 20, 141, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateEdit_5 = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit_5.setGeometry(QtCore.QRect(290, 60, 110, 22))
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(150, 60, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_16.setGeometry(QtCore.QRect(610, 60, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(700, 60, 121, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(10, 130, 821, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(10, 480, 831, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tabWidgetPorocilo.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_GenerirajPorocilo = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_GenerirajPorocilo.setGeometry(QtCore.QRect(370, 80, 101, 23))
        self.pushButton_GenerirajPorocilo.setObjectName("pushButton_GenerirajPorocilo")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(40, 50, 41, 16))
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(140, 50, 61, 16))
        self.label_22.setObjectName("label_22")
        self.comboBoxZaposleniPorocilo = QtWidgets.QComboBox(self.tab_3)
        self.comboBoxZaposleniPorocilo.setGeometry(QtCore.QRect(30, 80, 71, 20))
        self.comboBoxZaposleniPorocilo.setEditable(False)
        self.comboBoxZaposleniPorocilo.setCurrentText("")
        self.comboBoxZaposleniPorocilo.setObjectName("comboBoxZaposleniPorocilo")
        self.dateEdit_DatumDoPorocilo = QtWidgets.QDateEdit(self.tab_3)
        self.dateEdit_DatumDoPorocilo.setGeometry(QtCore.QRect(240, 80, 110, 22))
        self.dateEdit_DatumDoPorocilo.setObjectName("dateEdit_DatumDoPorocilo")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(270, 50, 47, 13))
        self.label_23.setObjectName("label_23")
        self.dateEdit_DatumOdPorocilo = QtWidgets.QDateEdit(self.tab_3)
        self.dateEdit_DatumOdPorocilo.setGeometry(QtCore.QRect(120, 80, 110, 22))
        self.dateEdit_DatumOdPorocilo.setObjectName("dateEdit_DatumOdPorocilo")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(20, 210, 791, 491))
        self.textEdit.setObjectName("textEdit")
        self.tabWidgetPorocilo.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetPorocilo.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_delete.setText(_translate("MainWindow", "Izbriši izbrano"))
        self.pushButton_popravi.setText(_translate("MainWindow", "Popravi izbrano"))
        self.pushButton_Iskanje.setText(_translate("MainWindow", "Iskanje"))
        self.radioButton_ASC.setText(_translate("MainWindow", "Naraščajoče"))
        self.radioButton_DSC.setText(_translate("MainWindow", "Padajoče"))
        self.label.setText(_translate("MainWindow", "Ime"))
        self.label_2.setText(_translate("MainWindow", "Datum od:"))
        self.label_3.setText(_translate("MainWindow", "Datum do:"))
        self.label_4.setText(_translate("MainWindow", "Razvrsti po :"))
        self.label_5.setText(_translate("MainWindow", "Datum:"))
        self.pushButton_izberiNapako.setText(_translate("MainWindow", "Pokaži napako"))
        self.label_8.setText(_translate("MainWindow", "Nov vnos:"))
        self.pushButton_VnosDogodka.setText(_translate("MainWindow", "Vnesi"))
        self.label_9.setText(_translate("MainWindow", "Ime:"))
        self.label_10.setText(_translate("MainWindow", "Datum:"))
        self.label_11.setText(_translate("MainWindow", "Ura:"))
        self.label_12.setText(_translate("MainWindow", "Dogodek:"))
        self.checkBox_zposleni.setText(_translate("MainWindow", "Zaposlenem"))
        self.radioButton_Vse.setText(_translate("MainWindow", "Vse"))
        self.radioButton_odhod.setText(_translate("MainWindow", "Odhode"))
        self.radioButton_prihod.setText(_translate("MainWindow", "Prihode"))
        self.label_14.setText(_translate("MainWindow", "Prikaži:"))
        self.label_15.setText(_translate("MainWindow", "Ime:"))
        self.label_16.setText(_translate("MainWindow", "Datum:"))
        self.label_17.setText(_translate("MainWindow", "Ura:"))
        self.label_18.setText(_translate("MainWindow", "Dogodek:"))
        self.popravi_sporocilo.setText(_translate("MainWindow", ":"))
        self.vnos_sporocilo.setText(_translate("MainWindow", ":"))
        self.pushButton_izberiSpremeni.setText(_translate("MainWindow", "Izberi za spreminjanje"))
        self.label_6.setText(_translate("MainWindow", "Vsota ur:"))
        self.label_7.setText(_translate("MainWindow", "Zajet časovni iterval:"))
        self.label_vsota1.setText(_translate("MainWindow", ":"))
        self.label_vsota2.setText(_translate("MainWindow", ":"))
        self.label_21.setText(_translate("MainWindow", "Od:"))
        self.label_datumIntOd.setText(_translate("MainWindow", ":"))
        self.label_datumIntDo.setText(_translate("MainWindow", ":"))
        self.label_24.setText(_translate("MainWindow", "Do:"))
        self.pushButton_resetfilter.setText(_translate("MainWindow", "Počisti filter"))
        self.pushButton_izracunajPonovno.setText(_translate("MainWindow", "Izračunaj ponovno"))
        self.label_19.setText(_translate("MainWindow", "Napaka:"))
        self.label_napaka.setText(_translate("MainWindow", ":"))
        self.label_sporociloVsotaUr.setText(_translate("MainWindow", ":"))
        self.tabWidgetPorocilo.setTabText(self.tabWidgetPorocilo.indexOf(self.tab), _translate("MainWindow", "Iskanje in upravljanje podatkov"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "Izbriši zaposlenega"))
        self.pushButton_14.setText(_translate("MainWindow", "Popravi inforamcije"))
        self.pushButton_15.setText(_translate("MainWindow", "Zamenjaj čip"))
        self.label_13.setText(_translate("MainWindow", "Vnos novega zaposlenega:"))
        self.pushButton_16.setText(_translate("MainWindow", "Vnesi čip"))
        self.pushButton_17.setText(_translate("MainWindow", "Dodaj zaposlenega"))
        self.tabWidgetPorocilo.setTabText(self.tabWidgetPorocilo.indexOf(self.tab_2), _translate("MainWindow", "Zaposleni"))
        self.pushButton_GenerirajPorocilo.setText(_translate("MainWindow", "Generiraj Poročilo"))
        self.label_20.setText(_translate("MainWindow", "Ime"))
        self.label_22.setText(_translate("MainWindow", "Datum od:"))
        self.label_23.setText(_translate("MainWindow", "Datum do:"))
        self.tabWidgetPorocilo.setTabText(self.tabWidgetPorocilo.indexOf(self.tab_3), _translate("MainWindow", "Poročila"))

