# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timestamp_window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 771, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(190, 40, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cas = QtWidgets.QLabel(self.frame)
        self.cas.setGeometry(QtCore.QRect(600, 0, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.cas.setFont(font)
        self.cas.setObjectName("cas")
        self.datum = QtWidgets.QLabel(self.frame)
        self.datum.setGeometry(QtCore.QRect(0, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.datum.setFont(font)
        self.datum.setObjectName("datum")
        self.pushButtonPrihod = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPrihod.setGeometry(QtCore.QRect(10, 290, 250, 250))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButtonPrihod.setFont(font)
        self.pushButtonPrihod.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonPrihod.setObjectName("pushButtonPrihod")
        self.pushButtonOdhod = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOdhod.setGeometry(QtCore.QRect(270, 290, 250, 250))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButtonOdhod.setFont(font)
        self.pushButtonOdhod.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonOdhod.setObjectName("pushButtonOdhod")
        self.pushButtonInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonInfo.setEnabled(True)
        self.pushButtonInfo.setGeometry(QtCore.QRect(530, 290, 250, 250))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButtonInfo.setFont(font)
        self.pushButtonInfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonInfo.setObjectName("pushButtonInfo")
        self.vnos = QtWidgets.QLineEdit(self.centralwidget)
        self.vnos.setGeometry(QtCore.QRect(50, 160, 121, 41))
        self.vnos.setObjectName("vnos")
        self.izpis = QtWidgets.QLabel(self.centralwidget)
        self.izpis.setGeometry(QtCore.QRect(220, 140, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.izpis.setFont(font)
        self.izpis.setObjectName("izpis")
        self.izpis2 = QtWidgets.QLabel(self.centralwidget)
        self.izpis2.setGeometry(QtCore.QRect(220, 190, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.izpis2.setFont(font)
        self.izpis2.setObjectName("izpis2")
        self.sporocilo = QtWidgets.QLabel(self.centralwidget)
        self.sporocilo.setGeometry(QtCore.QRect(40, 310, 721, 211))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.sporocilo.setFont(font)
        self.sporocilo.setText("")
        self.sporocilo.setObjectName("sporocilo")
        self.sporocilo.raise_()
        self.frame.raise_()
        self.pushButtonPrihod.raise_()
        self.pushButtonOdhod.raise_()
        self.pushButtonInfo.raise_()
        self.vnos.raise_()
        self.izpis.raise_()
        self.izpis2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "DR.STOM  Registracija delovnega časa"))
        self.cas.setText(_translate("MainWindow", "20:33:50"))
        self.datum.setText(_translate("MainWindow", "20.3.2018"))
        self.pushButtonPrihod.setText(_translate("MainWindow", "Prihod"))
        self.pushButtonOdhod.setText(_translate("MainWindow", "Odhod"))
        self.pushButtonInfo.setText(_translate("MainWindow", "Info"))
        self.izpis.setText(_translate("MainWindow", "Pozdravljeni/a"))
        self.izpis2.setText(_translate("MainWindow", "Zadnja registracija:"))

